
// This file has been generated by the GUI designer. Do not modify.
namespace Serpis.Ad
{
	public partial class CategoriaListView
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Serpis.Ad.CategoriaListView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Serpis.Ad.CategoriaListView";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
